In [ ]:
sales = np.array([
    100 1500,900,1800,
    2100,1300,1700,800,
    2500,1600
])
np.mean(sales[sales>1500:sales<2000])


In [ ]:
sales - np.array([1200,1500,900,1800,2100])


In [ ]:
np.array([1,2,3,4,6,7,8,9,.....)]
#ham aese kitna hi likhe ge aise slove karne ke liye hai ham yah entry hoti hai np.arange()
         

In [2]:
import numpy as np
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
#np.arange(start,stop,step)
np.arange(1 , 50, 1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [4]:
np.arange(1,40,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [5]:
np.arange(1,80,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76])

In [7]:
import numpy as np
x = np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [9]:
x = np.linspace(0,20,4)
print(x)

[ 0.          6.66666667 13.33333333 20.        ]


In [10]:
np.arange(0,11,2)


array([ 0,  2,  4,  6,  8, 10])

In [15]:
import numpy as np
temperature = np.linspace(20,100,9)
print(temperature)

[ 20.  30.  40.  50.  60.  70.  80.  90. 100.]
