In [3]:
import torch 
x = torch.arange(12)
print(x.shape)
x = x.reshape(3,4)

print(x)
print(x.shape)

torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [6]:
x = torch.tensor([
    [1,2,3],
    [4,5,6],
])

print(x[:, :1])


tensor([[1],
        [4]])


In [7]:
x = torch.tensor([
    [1,2,3],
    [4,5,6],
])
print(x[:, :2])

tensor([[1, 2],
        [4, 5]])


In [8]:
x = torch.tensor([
    [1,2,3],
    [4,5,6],
])
print(x[:, :3])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
#test 3 

x = torch.tensor([
    [1.,2.,3.],
    [4.,5.,6.],
])
b = torch.tensor([10,20,30])
print(x+b)

tensor([[11., 22., 33.],
        [14., 25., 36.]])


In [10]:
x = torch.arange(24)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [11]:
x = torch.arange(40)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39])


In [16]:
#Element wise multipliation

a = torch.tensor([1,2,30])
b = torch.tensor([4,5,6])


c = a*b
print(c)





tensor([  4,  10, 180])


In [17]:
a = torch.tensor([1,1,1])
b = torch.tensor([2,2,2])

c = a@b
print(c)

tensor(6)


In [19]:
x = torch.tensor ([
    [1,2,3,],
    [4,5,6]
])

w = torch.tensor([10,20,30])
y = x@w
print(y)


tensor([140, 320])


In [21]:
# a mini neural layer 

x = torch.tensor([
    [1., 2., 3.],
    [4., 5., 6.]
])

w =  torch.tensor([
    [0.1,0.2],
    [0.3,0.4],
    [0.5,0.6]
])
b = torch.tensor([1.,2.])

z = x@w+b
print(z)

tensor([[3.2000, 4.8000],
        [5.9000, 8.4000]])
