In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3] , dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# get dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#get shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
# get type
a.dtype

dtype('int16')

In [9]:
#get size
a.itemsize

2

In [10]:
#get total sixe
a.size *a.itemsize

6

In [11]:
a.nbytes

6

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a [1,-2]

np.int64(13)

In [14]:
#get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
#get a specific column
a[:,2]

array([ 3, 10])

In [16]:
# getting a little more fancy [startidex: endinedwz: atepsize
a[0,1:2:3]


array([2])

In [18]:
a [1,5]=20
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [21]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
#get specific element work outside in 
b [0,1,1]

np.int64(4)

In [23]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
Initializing Different Types of Arrays 


In [24]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [26]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.ones((4,2,2), dtype ='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [38]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [41]:
np.full((4,4),10,dtype='float=32')

TypeError: data type 'float=32' not understood

In [44]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [45]:
#any otoher number (full_like )
np.full(a.shape,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
np.full_like(a,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [48]:
#random deciamal numbers 
np.random.rand(4,2,3)

array([[[0.05424219, 0.5143847 , 0.9780033 ],
        [0.46629412, 0.52494972, 0.34509399]],

       [[0.6500211 , 0.05736978, 0.34922662],
        [0.42401631, 0.68776142, 0.34456468]],

       [[0.29294659, 0.39939724, 0.72853474],
        [0.83700975, 0.2841171 , 0.87363548]],

       [[0.51736326, 0.26856054, 0.16597562],
        [0.10239435, 0.71765369, 0.35754997]]])

In [52]:
#random Interger values 
np.random.randint(-4,7,size=(3,3))

array([[-2,  4,  5],
       [ 0,  3,  4],
       [ 6,  5,  4]], dtype=int32)

In [53]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
arr =np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [64]:
output = np.ones((5,5))
print(output) 

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output [1:4,1:-1] = z

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [67]:
a = np.array([1,2,3])
b = a 
b[0] = 100
print(a)


[100   2   3]


In [69]:
Mathemmatics

NameError: name 'Mathemmatics' is not defined

In [73]:
a = np.array([1,2,3])
print(a)

[1 2 3]


a +2


a + 2

In [ ]:
filedata >