In [1]:
#one neuron
z = np.dot(w , x) +b


NameError: name 'np' is not defined

In [1]:
import numpy as np

x = np.array([2,4,3])

w = np.array([
    [0.5, 0.2,-0.4],
    [-0.3,0.8,0.1],
    [0.7,-0.2,0.5]
])

b = np.array([0.5,-0.2,0.1])
z = np.dot(w , x) +b
print(z)

[1.1 2.7 2.2]


In [6]:
x  =np.array([2,4,3])

w = np.array([
    [0.5, 0.2,-0.4],
    [-0.3,0.8,0.1],
    [0.7,-0.2,0.5]
])

b = np.array([0.5,-0.2,0.1])
z = np.dot(w , x) +b
a = 1/(1+np.exp(-z))
print(a)
print(z)
    

[0.75026011 0.93702664 0.90024951]
[1.1 2.7 2.2]


In [8]:
w = np.array([
    [0.5, 0.2,-0.4],
    [-0.3,0.8,0.1],
    [0.7,-0.2,0.5]
])

x =  np.array([2 , 4,3])
b = np.array([0.5,-0.2,0.1])
z = np.dot(w,x) + b
a = 1/(1+np.exp(-z))
print(z)
print(a)

[1.1 2.7 2.2]
[0.75026011 0.93702664 0.90024951]


In [ ]:
import numpy as np
import math 
import pandas as pd
import pytorch as pt
import tensor 
