In [2]:
import torch

In [3]:
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [4]:
print(x.dtype)

torch.int64


In [5]:
x = torch.tensor([1,2,3])
print(x+10)

tensor([11, 12, 13])


In [6]:
print(x*10)

tensor([10, 20, 30])


In [7]:
print(x**2)

tensor([1, 4, 9])


In [8]:
import torch 
x = torch.tensor([2.,3.])
w = torch.tensor([0.5,0.8])
b = torch.tensor(1.)

z = torch.dot(w ,x ) + b

print(z)

tensor(4.4000)


In [13]:
x = torch.tensor([3. , 4.])
w = torch.tensor([0.2,0.7])
b = torch.tensor(2.)

a = torch.dot(w ,x ) +b 
print(a )
print(type(x))
print(x.shape)
print(x.ndim)
print(x.dtype)

tensor(5.4000)
<class 'torch.Tensor'>
torch.Size([2])
1
torch.float32


In [ ]:
12